apiVersion: 1.0.0
kind: Plugin
metadata:
  name: InfluxDB Storage
  description: InfluxDB storage plugin for Reekoh IoT Platform.
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - influx
  config:
    host:
      label: Host
      type: String
      maxLength: 1000
      required: true
      help: "Host for the InfluxDB database."
    port:
      label: Port
      type: Number
      required: false
      min: 1
      max: 65353
      default: 8086
      help: "(Optional) Port for the InfluxDB database. Default: 8086."
    protocol:
      label: Protocol
      type: String
      maxLength: 1000
      required: false
      enum:
        - http
        - https
      default: http
      help: "(Optional) Protocol to be used for the InfluxDB database connection. Default: http."
    username:
      label: Username
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) Username to be used for the InfluxDB database authentication"
    password:
      label: Password
      type: Password
      maxLength: 1000
      required: false
      help: "(Optional) Password to be used for the InfluxDB database authentication."
    database:
      label: Database Name
      type: String
      maxLength: 1000
      required: true
      help: "Database Name where the Series is located."
    series:
      label: Series name
      type: String
      maxLength: 1000
      required: true
      help: "Series Name where the data will be saved."
    tagKeys:
      label: Tag Keys
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) Field name in the Data that will be used for the Tag keys values should be comma separated ie (tag1,tag2,tag3)."

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??